name: Test matrix

on: [pull_request]

jobs:
  run:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: ['7.1', '7.2', '7.3', '7.4', '8.0']
        phpunit-versions: ['8.5', '8.5', '9.5', '9.5', '9.5']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer, phpunit:${{ matrix.phpunit-versions }}

      - name: Composer install
        run: |
          composer install

      - name: Run functionnal and unit tests
        run: |
          phpunit ./